using System;
using System.Diagnostics;
using System.IO;

namespace PylonStream
{
    public class MediaMTXManager
    {
        private Process? _process;
        private readonly object _lock = new object();

        public bool IsRunning
        {
            get
            {
                lock (_lock)
                {
                    if (_process == null) return false;
                    try
                    {
                        return !_process.HasExited;
                    }
                    catch
                    {
                        return false;
                    }
                }
            }
        }

        public void Start()
        {
            lock (_lock)
            {
                if (IsRunning)
                {
                    Modules.SystemLogger.AddLog("MediaMTX is already running.", "INFO");
                    return;
                }

                string exePath = Modules.Config.MediamtxPath;
                if (!Path.IsPathRooted(exePath))
                {
                    exePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, exePath);
                }

                if (!File.Exists(exePath))
                {
                    Modules.SystemLogger.AddLog($"MediaMTX executable not found at: {exePath}", "ERROR");
                    return;
                }

                try
                {
                    // Dynamically generate mediamtx.yml to synchronize ports and enable all paths
                    string configDir = Path.GetDirectoryName(exePath) ?? "";
                    string ymlPath = Path.Combine(configDir, "mediamtx.yml");
                    try
                    {
                        string ipBind = Modules.Config.SelectedInterfaceIp == "Auto" ? "" : Modules.Config.SelectedInterfaceIp;
                        string ymlContent = $@"# Auto-generated by PylonStreamer
rtspAddress: {ipBind}:{Modules.Config.MediamtxPort}
rtmpDisable: yes
hlsDisable: yes
webrtcAddress: {ipBind}:8889

paths:
  all:
";
                        File.WriteAllText(ymlPath, ymlContent);
                    }
                    catch (Exception ex)
                    {
                        Modules.SystemLogger.AddLog($"Failed to generate mediamtx.yml config: {ex.Message}", "WARN");
                    }

                    var startInfo = new ProcessStartInfo
                    {
                        FileName = exePath,
                        WorkingDirectory = configDir,
                        CreateNoWindow = true,
                        UseShellExecute = false,
                        RedirectStandardOutput = true,
                        RedirectStandardError = true
                    };

                    _process = new Process { StartInfo = startInfo };
                    _process.OutputDataReceived += (sender, e) =>
                    {
                        if (!string.IsNullOrEmpty(e.Data))
                        {
                            Modules.SystemLogger.AddLog($"MediaMTX: {e.Data.Trim()}", "INFO");
                        }
                    };
                    _process.ErrorDataReceived += (sender, e) =>
                    {
                        if (!string.IsNullOrEmpty(e.Data))
                        {
                            Modules.SystemLogger.AddLog($"MediaMTX Error: {e.Data.Trim()}", "WARN");
                        }
                    };

                    _process.Start();
                    _process.BeginOutputReadLine();
                    _process.BeginErrorReadLine();

                    Modules.SystemLogger.AddLog("MediaMTX process started successfully.", "INFO");
                }
                catch (Exception ex)
                {
                    Modules.SystemLogger.AddLog($"Failed to start MediaMTX process: {ex.Message}", "ERROR");
                }
            }
        }

        public void Stop()
        {
            lock (_lock)
            {
                if (_process == null) return;

                try
                {
                    if (!_process.HasExited)
                    {
                        _process.Kill(true); // Kill the entire process tree
                        Modules.SystemLogger.AddLog("MediaMTX process terminated.", "INFO");
                    }
                }
                catch (Exception ex)
                {
                    Modules.SystemLogger.AddLog($"Error stopping MediaMTX process: {ex.Message}", "WARN");
                }
                finally
                {
                    _process.Dispose();
                    _process = null;
                }
            }
        }
    }
}
